/**
 * ICP Controls Registry - Single source of truth for all control definitions
 */

import type { ControlDefinition, CategoryDefinition } from './types';

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: 'network',
    label: 'Network & Connection',
    description: 'Configure network endpoints and connection settings',
    icon: 'Network',
  },
  {
    id: 'agent',
    label: 'Agent Configuration',
    description: 'HTTP agent and request handling settings',
    icon: 'Settings',
  },
  {
    id: 'performance',
    label: 'Performance & Optimization',
    description: 'Tune performance, caching, and resource usage',
    icon: 'Zap',
  },
  {
    id: 'security',
    label: 'Security & Authentication',
    description: 'Security policies and authentication controls',
    icon: 'Shield',
  },
  {
    id: 'diagnostics',
    label: 'Diagnostics & Logging',
    description: 'Debug output, logging, and monitoring',
    icon: 'Activity',
  },
  {
    id: 'features',
    label: 'Feature Flags',
    description: 'Enable or disable experimental features',
    icon: 'Flag',
  },
  {
    id: 'experimental',
    label: 'Experimental',
    description: 'Cutting-edge features under development',
    icon: 'Beaker',
  },
  {
    id: 'advanced',
    label: 'Advanced Settings',
    description: 'Low-level configuration for experts',
    icon: 'Wrench',
  },
];

export const CONTROLS: ControlDefinition[] = [
  // Network & Connection (30 controls)
  {
    id: 'network',
    title: 'Network Environment',
    description: 'Select the Internet Computer network to connect to',
    keywords: ['network', 'environment', 'mainnet', 'local'],
    category: 'network',
    type: 'select',
    defaultValue: 'local',
    options: [
      { value: 'local', label: 'Local Development' },
      { value: 'mainnet', label: 'ICP Mainnet' },
    ],
  },
  {
    id: 'canisterId',
    title: 'Canister ID',
    description: 'Target canister principal identifier',
    keywords: ['canister', 'id', 'principal', 'target'],
    category: 'network',
    type: 'text',
    defaultValue: 'Not available',
    placeholder: 'Enter canister ID',
  },
  {
    id: 'agentHostPreset',
    title: 'Agent Host Preset',
    description: 'Predefined host configurations',
    keywords: ['host', 'preset', 'endpoint', 'url'],
    category: 'network',
    type: 'select',
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'Auto-detect' },
      { value: 'local', label: 'Local (127.0.0.1:4943)' },
      { value: 'mainnet', label: 'Mainnet (icp-api.io)' },
      { value: 'custom', label: 'Custom URL' },
    ],
  },
  {
    id: 'customAgentHost',
    title: 'Custom Agent Host',
    description: 'Custom HTTP agent host URL',
    keywords: ['custom', 'host', 'url', 'endpoint'],
    category: 'network',
    type: 'text',
    defaultValue: '',
    placeholder: 'https://custom-host.com',
  },
  {
    id: 'fetchRootKey',
    title: 'Fetch Root Key',
    description: 'Automatically fetch root key for local development',
    keywords: ['root', 'key', 'local', 'development'],
    category: 'network',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'verifyQuerySignatures',
    title: 'Verify Query Signatures',
    description: 'Enable cryptographic verification of query responses',
    keywords: ['verify', 'signature', 'query', 'security'],
    category: 'network',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'replicaVersion',
    title: 'Replica Version',
    description: 'Target Internet Computer replica version',
    keywords: ['replica', 'version', 'compatibility'],
    category: 'network',
    type: 'text',
    defaultValue: 'latest',
    placeholder: 'e.g., 0.8.0',
  },
  {
    id: 'subnetId',
    title: 'Subnet ID',
    description: 'Target specific subnet for canister calls',
    keywords: ['subnet', 'id', 'routing'],
    category: 'network',
    type: 'text',
    defaultValue: '',
    placeholder: 'Optional subnet principal',
  },
  {
    id: 'boundaryNode',
    title: 'Boundary Node',
    description: 'Preferred boundary node for requests',
    keywords: ['boundary', 'node', 'routing', 'edge'],
    category: 'network',
    type: 'select',
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'Auto-select' },
      { value: 'us-east', label: 'US East' },
      { value: 'us-west', label: 'US West' },
      { value: 'eu-central', label: 'EU Central' },
      { value: 'asia-pacific', label: 'Asia Pacific' },
    ],
  },
  {
    id: 'connectionMode',
    title: 'Connection Mode',
    description: 'HTTP connection behavior',
    keywords: ['connection', 'mode', 'http', 'persistent'],
    category: 'network',
    type: 'select',
    defaultValue: 'persistent',
    options: [
      { value: 'persistent', label: 'Persistent' },
      { value: 'per-request', label: 'Per Request' },
      { value: 'pooled', label: 'Connection Pool' },
    ],
  },
  {
    id: 'maxConnectionPoolSize',
    title: 'Max Connection Pool Size',
    description: 'Maximum number of pooled connections',
    keywords: ['pool', 'connection', 'limit', 'max'],
    category: 'network',
    type: 'number',
    defaultValue: 10,
    min: 1,
    max: 100,
  },
  {
    id: 'connectionIdleTimeout',
    title: 'Connection Idle Timeout',
    description: 'Seconds before idle connections are closed',
    keywords: ['idle', 'timeout', 'connection', 'close'],
    category: 'network',
    type: 'number',
    defaultValue: 60,
    min: 10,
    max: 600,
    unit: 'seconds',
  },
  {
    id: 'dnsResolutionMode',
    title: 'DNS Resolution Mode',
    description: 'How to resolve canister hostnames',
    keywords: ['dns', 'resolution', 'hostname'],
    category: 'network',
    type: 'select',
    defaultValue: 'standard',
    options: [
      { value: 'standard', label: 'Standard DNS' },
      { value: 'cached', label: 'Cached DNS' },
      { value: 'custom', label: 'Custom Resolver' },
    ],
  },
  {
    id: 'dnsCacheTtl',
    title: 'DNS Cache TTL',
    description: 'Time-to-live for DNS cache entries',
    keywords: ['dns', 'cache', 'ttl', 'expiry'],
    category: 'network',
    type: 'number',
    defaultValue: 300,
    min: 60,
    max: 3600,
    unit: 'seconds',
  },
  {
    id: 'ipVersion',
    title: 'IP Version Preference',
    description: 'Prefer IPv4 or IPv6 connections',
    keywords: ['ip', 'version', 'ipv4', 'ipv6'],
    category: 'network',
    type: 'select',
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'Auto' },
      { value: 'ipv4', label: 'IPv4 Only' },
      { value: 'ipv6', label: 'IPv6 Only' },
      { value: 'prefer-ipv4', label: 'Prefer IPv4' },
      { value: 'prefer-ipv6', label: 'Prefer IPv6' },
    ],
  },
  {
    id: 'proxyMode',
    title: 'Proxy Mode',
    description: 'Enable HTTP proxy for requests',
    keywords: ['proxy', 'http', 'tunnel'],
    category: 'network',
    type: 'select',
    defaultValue: 'none',
    options: [
      { value: 'none', label: 'No Proxy' },
      { value: 'system', label: 'System Proxy' },
      { value: 'custom', label: 'Custom Proxy' },
    ],
  },
  {
    id: 'proxyUrl',
    title: 'Proxy URL',
    description: 'Custom proxy server URL',
    keywords: ['proxy', 'url', 'server'],
    category: 'network',
    type: 'text',
    defaultValue: '',
    placeholder: 'http://proxy.example.com:8080',
  },
  {
    id: 'tlsVersion',
    title: 'TLS Version',
    description: 'Minimum TLS protocol version',
    keywords: ['tls', 'ssl', 'security', 'encryption'],
    category: 'network',
    type: 'select',
    defaultValue: 'tls1.2',
    options: [
      { value: 'tls1.2', label: 'TLS 1.2' },
      { value: 'tls1.3', label: 'TLS 1.3' },
    ],
  },
  {
    id: 'certificateValidation',
    title: 'Certificate Validation',
    description: 'Validate SSL/TLS certificates',
    keywords: ['certificate', 'ssl', 'tls', 'validation'],
    category: 'network',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'customCertificates',
    title: 'Custom Certificates',
    description: 'Use custom CA certificates',
    keywords: ['certificate', 'ca', 'custom', 'trust'],
    category: 'network',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'networkQualityMode',
    title: 'Network Quality Mode',
    description: 'Optimize for network conditions',
    keywords: ['network', 'quality', 'optimization'],
    category: 'network',
    type: 'select',
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'Auto-detect' },
      { value: 'high-speed', label: 'High Speed' },
      { value: 'low-latency', label: 'Low Latency' },
      { value: 'unreliable', label: 'Unreliable Network' },
    ],
  },
  {
    id: 'compressionMode',
    title: 'Compression Mode',
    description: 'HTTP compression for requests/responses',
    keywords: ['compression', 'gzip', 'deflate'],
    category: 'network',
    type: 'select',
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'Auto' },
      { value: 'gzip', label: 'GZIP' },
      { value: 'deflate', label: 'Deflate' },
      { value: 'none', label: 'No Compression' },
    ],
  },
  {
    id: 'keepAlive',
    title: 'Keep-Alive',
    description: 'Enable HTTP keep-alive connections',
    keywords: ['keepalive', 'persistent', 'connection'],
    category: 'network',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'keepAliveTimeout',
    title: 'Keep-Alive Timeout',
    description: 'Keep-alive timeout in seconds',
    keywords: ['keepalive', 'timeout', 'connection'],
    category: 'network',
    type: 'number',
    defaultValue: 30,
    min: 5,
    max: 300,
    unit: 'seconds',
  },
  {
    id: 'maxRedirects',
    title: 'Max Redirects',
    description: 'Maximum HTTP redirects to follow',
    keywords: ['redirect', 'http', 'limit'],
    category: 'network',
    type: 'number',
    defaultValue: 5,
    min: 0,
    max: 20,
  },
  {
    id: 'followRedirects',
    title: 'Follow Redirects',
    description: 'Automatically follow HTTP redirects',
    keywords: ['redirect', 'follow', 'http'],
    category: 'network',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'userAgent',
    title: 'User Agent',
    description: 'Custom HTTP User-Agent header',
    keywords: ['user', 'agent', 'header', 'http'],
    category: 'network',
    type: 'text',
    defaultValue: 'ICP-Agent/1.0',
    placeholder: 'Custom user agent string',
  },
  {
    id: 'customHeaders',
    title: 'Custom Headers',
    description: 'Additional HTTP headers (JSON format)',
    keywords: ['headers', 'http', 'custom'],
    category: 'network',
    type: 'textarea',
    defaultValue: '{}',
    placeholder: '{"X-Custom-Header": "value"}',
  },
  {
    id: 'corsMode',
    title: 'CORS Mode',
    description: 'Cross-Origin Resource Sharing mode',
    keywords: ['cors', 'cross-origin', 'security'],
    category: 'network',
    type: 'select',
    defaultValue: 'cors',
    options: [
      { value: 'cors', label: 'CORS' },
      { value: 'no-cors', label: 'No CORS' },
      { value: 'same-origin', label: 'Same Origin' },
    ],
  },
  {
    id: 'credentialsMode',
    title: 'Credentials Mode',
    description: 'Include credentials in requests',
    keywords: ['credentials', 'cookies', 'auth'],
    category: 'network',
    type: 'select',
    defaultValue: 'same-origin',
    options: [
      { value: 'omit', label: 'Omit' },
      { value: 'same-origin', label: 'Same Origin' },
      { value: 'include', label: 'Include' },
    ],
  },

  // Agent Configuration (25 controls)
  {
    id: 'requestTimeout',
    title: 'Request Timeout',
    description: 'Maximum time to wait for a response',
    keywords: ['timeout', 'request', 'wait', 'duration'],
    category: 'agent',
    type: 'number',
    defaultValue: 30000,
    min: 1000,
    max: 300000,
    unit: 'milliseconds',
  },
  {
    id: 'pollingInterval',
    title: 'Polling Interval',
    description: 'Interval for polling update call status',
    keywords: ['polling', 'interval', 'update', 'status'],
    category: 'agent',
    type: 'number',
    defaultValue: 1000,
    min: 100,
    max: 10000,
    unit: 'milliseconds',
  },
  {
    id: 'maxPollingAttempts',
    title: 'Max Polling Attempts',
    description: 'Maximum number of polling attempts',
    keywords: ['polling', 'max', 'attempts', 'limit'],
    category: 'agent',
    type: 'number',
    defaultValue: 60,
    min: 1,
    max: 300,
  },
  {
    id: 'retryCount',
    title: 'Retry Count',
    description: 'Number of retry attempts for failed requests',
    keywords: ['retry', 'attempts', 'failure', 'resilience'],
    category: 'agent',
    type: 'number',
    defaultValue: 3,
    min: 0,
    max: 10,
  },
  {
    id: 'retryBackoff',
    title: 'Retry Backoff',
    description: 'Backoff strategy for retries',
    keywords: ['retry', 'backoff', 'exponential', 'delay'],
    category: 'agent',
    type: 'select',
    defaultValue: 'exponential',
    options: [
      { value: 'none', label: 'No Backoff' },
      { value: 'linear', label: 'Linear' },
      { value: 'exponential', label: 'Exponential' },
      { value: 'fibonacci', label: 'Fibonacci' },
    ],
  },
  {
    id: 'retryDelay',
    title: 'Initial Retry Delay',
    description: 'Initial delay before first retry',
    keywords: ['retry', 'delay', 'initial', 'wait'],
    category: 'agent',
    type: 'number',
    defaultValue: 1000,
    min: 100,
    max: 10000,
    unit: 'milliseconds',
  },
  {
    id: 'maxRetryDelay',
    title: 'Max Retry Delay',
    description: 'Maximum delay between retries',
    keywords: ['retry', 'delay', 'max', 'limit'],
    category: 'agent',
    type: 'number',
    defaultValue: 30000,
    min: 1000,
    max: 120000,
    unit: 'milliseconds',
  },
  {
    id: 'retryOnTimeout',
    title: 'Retry on Timeout',
    description: 'Retry requests that timeout',
    keywords: ['retry', 'timeout', 'failure'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'retryOnNetworkError',
    title: 'Retry on Network Error',
    description: 'Retry requests with network errors',
    keywords: ['retry', 'network', 'error', 'failure'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'retryOn5xx',
    title: 'Retry on 5xx Errors',
    description: 'Retry requests with server errors',
    keywords: ['retry', '5xx', 'server', 'error'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'retryOn429',
    title: 'Retry on Rate Limit',
    description: 'Retry requests that are rate limited',
    keywords: ['retry', '429', 'rate', 'limit'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'callTransform',
    title: 'Call Transform',
    description: 'Enable call transformation for responses',
    keywords: ['transform', 'call', 'response'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'ingressExpiry',
    title: 'Ingress Expiry',
    description: 'Ingress message expiry time',
    keywords: ['ingress', 'expiry', 'timeout'],
    category: 'agent',
    type: 'number',
    defaultValue: 300000,
    min: 60000,
    max: 600000,
    unit: 'milliseconds',
  },
  {
    id: 'nonceGeneration',
    title: 'Nonce Generation',
    description: 'Strategy for generating request nonces',
    keywords: ['nonce', 'generation', 'random'],
    category: 'agent',
    type: 'select',
    defaultValue: 'random',
    options: [
      { value: 'random', label: 'Random' },
      { value: 'sequential', label: 'Sequential' },
      { value: 'timestamp', label: 'Timestamp-based' },
    ],
  },
  {
    id: 'batchRequests',
    title: 'Batch Requests',
    description: 'Enable request batching',
    keywords: ['batch', 'requests', 'optimization'],
    category: 'agent',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'batchSize',
    title: 'Batch Size',
    description: 'Maximum requests per batch',
    keywords: ['batch', 'size', 'limit'],
    category: 'agent',
    type: 'number',
    defaultValue: 10,
    min: 2,
    max: 50,
  },
  {
    id: 'batchDelay',
    title: 'Batch Delay',
    description: 'Delay before sending batch',
    keywords: ['batch', 'delay', 'wait'],
    category: 'agent',
    type: 'number',
    defaultValue: 100,
    min: 10,
    max: 1000,
    unit: 'milliseconds',
  },
  {
    id: 'requestPriority',
    title: 'Request Priority',
    description: 'Default priority for requests',
    keywords: ['priority', 'request', 'queue'],
    category: 'agent',
    type: 'select',
    defaultValue: 'normal',
    options: [
      { value: 'low', label: 'Low' },
      { value: 'normal', label: 'Normal' },
      { value: 'high', label: 'High' },
      { value: 'critical', label: 'Critical' },
    ],
  },
  {
    id: 'concurrentRequests',
    title: 'Concurrent Requests',
    description: 'Maximum concurrent requests',
    keywords: ['concurrent', 'parallel', 'limit'],
    category: 'agent',
    type: 'number',
    defaultValue: 6,
    min: 1,
    max: 20,
  },
  {
    id: 'requestQueue',
    title: 'Request Queue',
    description: 'Enable request queuing',
    keywords: ['queue', 'requests', 'buffer'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'queueSize',
    title: 'Queue Size',
    description: 'Maximum queued requests',
    keywords: ['queue', 'size', 'limit'],
    category: 'agent',
    type: 'number',
    defaultValue: 100,
    min: 10,
    max: 1000,
  },
  {
    id: 'queueStrategy',
    title: 'Queue Strategy',
    description: 'Request queue processing strategy',
    keywords: ['queue', 'strategy', 'fifo', 'lifo'],
    category: 'agent',
    type: 'select',
    defaultValue: 'fifo',
    options: [
      { value: 'fifo', label: 'First In First Out' },
      { value: 'lifo', label: 'Last In First Out' },
      { value: 'priority', label: 'Priority-based' },
    ],
  },
  {
    id: 'responseValidation',
    title: 'Response Validation',
    description: 'Validate response structure',
    keywords: ['validation', 'response', 'check'],
    category: 'agent',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'strictMode',
    title: 'Strict Mode',
    description: 'Enable strict validation and error checking',
    keywords: ['strict', 'validation', 'errors'],
    category: 'agent',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'errorHandling',
    title: 'Error Handling',
    description: 'Error handling strategy',
    keywords: ['error', 'handling', 'strategy'],
    category: 'agent',
    type: 'select',
    defaultValue: 'throw',
    options: [
      { value: 'throw', label: 'Throw Errors' },
      { value: 'return', label: 'Return Errors' },
      { value: 'callback', label: 'Error Callback' },
    ],
  },

  // Performance & Optimization (30 controls)
  {
    id: 'cacheMode',
    title: 'Cache Mode',
    description: 'Response caching strategy',
    keywords: ['cache', 'caching', 'performance'],
    category: 'performance',
    type: 'select',
    defaultValue: 'default',
    options: [
      { value: 'default', label: 'Default' },
      { value: 'no-cache', label: 'No Cache' },
      { value: 'force-cache', label: 'Force Cache' },
      { value: 'only-if-cached', label: 'Only If Cached' },
    ],
  },
  {
    id: 'cacheTtl',
    title: 'Cache TTL',
    description: 'Cache time-to-live',
    keywords: ['cache', 'ttl', 'expiry'],
    category: 'performance',
    type: 'number',
    defaultValue: 300,
    min: 0,
    max: 3600,
    unit: 'seconds',
  },
  {
    id: 'cacheSize',
    title: 'Cache Size',
    description: 'Maximum cache entries',
    keywords: ['cache', 'size', 'limit'],
    category: 'performance',
    type: 'number',
    defaultValue: 100,
    min: 0,
    max: 1000,
  },
  {
    id: 'cacheStrategy',
    title: 'Cache Strategy',
    description: 'Cache eviction strategy',
    keywords: ['cache', 'eviction', 'lru', 'lfu'],
    category: 'performance',
    type: 'select',
    defaultValue: 'lru',
    options: [
      { value: 'lru', label: 'Least Recently Used' },
      { value: 'lfu', label: 'Least Frequently Used' },
      { value: 'fifo', label: 'First In First Out' },
    ],
  },
  {
    id: 'prefetchMode',
    title: 'Prefetch Mode',
    description: 'Enable response prefetching',
    keywords: ['prefetch', 'preload', 'optimization'],
    category: 'performance',
    type: 'select',
    defaultValue: 'none',
    options: [
      { value: 'none', label: 'Disabled' },
      { value: 'aggressive', label: 'Aggressive' },
      { value: 'conservative', label: 'Conservative' },
    ],
  },
  {
    id: 'lazyLoading',
    title: 'Lazy Loading',
    description: 'Enable lazy loading for resources',
    keywords: ['lazy', 'loading', 'defer'],
    category: 'performance',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'preconnect',
    title: 'Preconnect',
    description: 'Preconnect to backend hosts',
    keywords: ['preconnect', 'dns', 'optimization'],
    category: 'performance',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'resourceHints',
    title: 'Resource Hints',
    description: 'Enable resource hints (prefetch, preload)',
    keywords: ['hints', 'prefetch', 'preload'],
    category: 'performance',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'compressionLevel',
    title: 'Compression Level',
    description: 'Data compression level',
    keywords: ['compression', 'level', 'gzip'],
    category: 'performance',
    type: 'slider',
    defaultValue: 6,
    min: 1,
    max: 9,
  },
  {
    id: 'minifyResponses',
    title: 'Minify Responses',
    description: 'Minify JSON responses',
    keywords: ['minify', 'json', 'optimization'],
    category: 'performance',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'streamingMode',
    title: 'Streaming Mode',
    description: 'Enable response streaming',
    keywords: ['streaming', 'chunked', 'transfer'],
    category: 'performance',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'chunkSize',
    title: 'Chunk Size',
    description: 'Size of streaming chunks',
    keywords: ['chunk', 'size', 'streaming'],
    category: 'performance',
    type: 'number',
    defaultValue: 8192,
    min: 1024,
    max: 65536,
    unit: 'bytes',
  },
  {
    id: 'bufferSize',
    title: 'Buffer Size',
    description: 'Internal buffer size',
    keywords: ['buffer', 'size', 'memory'],
    category: 'performance',
    type: 'number',
    defaultValue: 16384,
    min: 4096,
    max: 131072,
    unit: 'bytes',
  },
  {
    id: 'memoryLimit',
    title: 'Memory Limit',
    description: 'Maximum memory usage',
    keywords: ['memory', 'limit', 'ram'],
    category: 'performance',
    type: 'number',
    defaultValue: 100,
    min: 10,
    max: 1000,
    unit: 'MB',
  },
  {
    id: 'gcMode',
    title: 'Garbage Collection Mode',
    description: 'Memory garbage collection strategy',
    keywords: ['gc', 'garbage', 'collection', 'memory'],
    category: 'performance',
    type: 'select',
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'Automatic' },
      { value: 'aggressive', label: 'Aggressive' },
      { value: 'lazy', label: 'Lazy' },
      { value: 'manual', label: 'Manual' },
    ],
  },
  {
    id: 'workerThreads',
    title: 'Worker Threads',
    description: 'Number of worker threads',
    keywords: ['worker', 'threads', 'parallel'],
    category: 'performance',
    type: 'number',
    defaultValue: 4,
    min: 1,
    max: 16,
  },
  {
    id: 'asyncMode',
    title: 'Async Mode',
    description: 'Asynchronous operation mode',
    keywords: ['async', 'parallel', 'concurrent'],
    category: 'performance',
    type: 'select',
    defaultValue: 'parallel',
    options: [
      { value: 'sequential', label: 'Sequential' },
      { value: 'parallel', label: 'Parallel' },
      { value: 'adaptive', label: 'Adaptive' },
    ],
  },
  {
    id: 'throttleRate',
    title: 'Throttle Rate',
    description: 'Request throttling rate',
    keywords: ['throttle', 'rate', 'limit'],
    category: 'performance',
    type: 'number',
    defaultValue: 100,
    min: 1,
    max: 1000,
    unit: 'req/sec',
  },
  {
    id: 'debounceDelay',
    title: 'Debounce Delay',
    description: 'Debounce delay for rapid requests',
    keywords: ['debounce', 'delay', 'throttle'],
    category: 'performance',
    type: 'number',
    defaultValue: 300,
    min: 0,
    max: 2000,
    unit: 'milliseconds',
  },
  {
    id: 'optimizationLevel',
    title: 'Optimization Level',
    description: 'Overall optimization level',
    keywords: ['optimization', 'level', 'performance'],
    category: 'performance',
    type: 'select',
    defaultValue: 'balanced',
    options: [
      { value: 'none', label: 'None' },
      { value: 'minimal', label: 'Minimal' },
      { value: 'balanced', label: 'Balanced' },
      { value: 'aggressive', label: 'Aggressive' },
    ],
  },
  {
    id: 'cpuAffinity',
    title: 'CPU Affinity',
    description: 'Pin operations to specific CPU cores',
    keywords: ['cpu', 'affinity', 'cores'],
    category: 'performance',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'priorityScheduling',
    title: 'Priority Scheduling',
    description: 'Enable priority-based task scheduling',
    keywords: ['priority', 'scheduling', 'tasks'],
    category: 'performance',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'loadBalancing',
    title: 'Load Balancing',
    description: 'Load balancing strategy',
    keywords: ['load', 'balancing', 'distribution'],
    category: 'performance',
    type: 'select',
    defaultValue: 'round-robin',
    options: [
      { value: 'round-robin', label: 'Round Robin' },
      { value: 'least-connections', label: 'Least Connections' },
      { value: 'random', label: 'Random' },
      { value: 'weighted', label: 'Weighted' },
    ],
  },
  {
    id: 'circuitBreaker',
    title: 'Circuit Breaker',
    description: 'Enable circuit breaker pattern',
    keywords: ['circuit', 'breaker', 'resilience'],
    category: 'performance',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'circuitBreakerThreshold',
    title: 'Circuit Breaker Threshold',
    description: 'Failure threshold to open circuit',
    keywords: ['circuit', 'breaker', 'threshold'],
    category: 'performance',
    type: 'number',
    defaultValue: 5,
    min: 1,
    max: 20,
  },
  {
    id: 'circuitBreakerTimeout',
    title: 'Circuit Breaker Timeout',
    description: 'Time before attempting to close circuit',
    keywords: ['circuit', 'breaker', 'timeout'],
    category: 'performance',
    type: 'number',
    defaultValue: 30000,
    min: 5000,
    max: 300000,
    unit: 'milliseconds',
  },
  {
    id: 'bulkheadSize',
    title: 'Bulkhead Size',
    description: 'Bulkhead pattern partition size',
    keywords: ['bulkhead', 'isolation', 'partition'],
    category: 'performance',
    type: 'number',
    defaultValue: 10,
    min: 1,
    max: 50,
  },
  {
    id: 'rateLimitWindow',
    title: 'Rate Limit Window',
    description: 'Time window for rate limiting',
    keywords: ['rate', 'limit', 'window'],
    category: 'performance',
    type: 'number',
    defaultValue: 60,
    min: 1,
    max: 3600,
    unit: 'seconds',
  },
  {
    id: 'rateLimitMax',
    title: 'Rate Limit Max',
    description: 'Maximum requests per window',
    keywords: ['rate', 'limit', 'max'],
    category: 'performance',
    type: 'number',
    defaultValue: 100,
    min: 1,
    max: 10000,
  },
  {
    id: 'adaptiveThrottling',
    title: 'Adaptive Throttling',
    description: 'Automatically adjust throttling based on load',
    keywords: ['adaptive', 'throttling', 'dynamic'],
    category: 'performance',
    type: 'boolean',
    defaultValue: true,
  },

  // Security & Authentication (30 controls)
  {
    id: 'authMode',
    title: 'Authentication Mode',
    description: 'Authentication method',
    keywords: ['auth', 'authentication', 'identity'],
    category: 'security',
    type: 'select',
    defaultValue: 'internet-identity',
    options: [
      { value: 'internet-identity', label: 'Internet Identity' },
      { value: 'anonymous', label: 'Anonymous' },
      { value: 'delegated', label: 'Delegated' },
    ],
  },
  {
    id: 'identityProvider',
    title: 'Identity Provider',
    description: 'Identity provider URL',
    keywords: ['identity', 'provider', 'idp'],
    category: 'security',
    type: 'text',
    defaultValue: 'https://identity.ic0.app',
    placeholder: 'Identity provider URL',
  },
  {
    id: 'delegationExpiry',
    title: 'Delegation Expiry',
    description: 'Delegation chain expiry time',
    keywords: ['delegation', 'expiry', 'timeout'],
    category: 'security',
    type: 'number',
    defaultValue: 28800000,
    min: 3600000,
    max: 86400000,
    unit: 'milliseconds',
  },
  {
    id: 'maxDelegationChainLength',
    title: 'Max Delegation Chain Length',
    description: 'Maximum delegation chain depth',
    keywords: ['delegation', 'chain', 'length'],
    category: 'security',
    type: 'number',
    defaultValue: 10,
    min: 1,
    max: 50,
  },
  {
    id: 'signatureVerification',
    title: 'Signature Verification',
    description: 'Verify all response signatures',
    keywords: ['signature', 'verification', 'crypto'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'certificateVerification',
    title: 'Certificate Verification',
    description: 'Verify canister certificates',
    keywords: ['certificate', 'verification', 'trust'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'nonceValidation',
    title: 'Nonce Validation',
    description: 'Validate request nonces',
    keywords: ['nonce', 'validation', 'replay'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'replayProtection',
    title: 'Replay Protection',
    description: 'Enable replay attack protection',
    keywords: ['replay', 'protection', 'security'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'csrfProtection',
    title: 'CSRF Protection',
    description: 'Enable CSRF token validation',
    keywords: ['csrf', 'protection', 'token'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'xssProtection',
    title: 'XSS Protection',
    description: 'Enable XSS filtering',
    keywords: ['xss', 'protection', 'filter'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'contentSecurityPolicy',
    title: 'Content Security Policy',
    description: 'Enable CSP headers',
    keywords: ['csp', 'security', 'policy'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'strictTransportSecurity',
    title: 'Strict Transport Security',
    description: 'Enable HSTS',
    keywords: ['hsts', 'transport', 'security'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'encryptionMode',
    title: 'Encryption Mode',
    description: 'Data encryption mode',
    keywords: ['encryption', 'crypto', 'security'],
    category: 'security',
    type: 'select',
    defaultValue: 'tls',
    options: [
      { value: 'none', label: 'None' },
      { value: 'tls', label: 'TLS Only' },
      { value: 'end-to-end', label: 'End-to-End' },
    ],
  },
  {
    id: 'keyRotation',
    title: 'Key Rotation',
    description: 'Enable automatic key rotation',
    keywords: ['key', 'rotation', 'crypto'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'keyRotationInterval',
    title: 'Key Rotation Interval',
    description: 'Key rotation interval',
    keywords: ['key', 'rotation', 'interval'],
    category: 'security',
    type: 'number',
    defaultValue: 86400,
    min: 3600,
    max: 604800,
    unit: 'seconds',
  },
  {
    id: 'sessionTimeout',
    title: 'Session Timeout',
    description: 'Session inactivity timeout',
    keywords: ['session', 'timeout', 'expiry'],
    category: 'security',
    type: 'number',
    defaultValue: 1800,
    min: 300,
    max: 7200,
    unit: 'seconds',
  },
  {
    id: 'maxSessions',
    title: 'Max Concurrent Sessions',
    description: 'Maximum concurrent sessions per user',
    keywords: ['session', 'max', 'concurrent'],
    category: 'security',
    type: 'number',
    defaultValue: 5,
    min: 1,
    max: 20,
  },
  {
    id: 'ipWhitelist',
    title: 'IP Whitelist',
    description: 'Allowed IP addresses (comma-separated)',
    keywords: ['ip', 'whitelist', 'access'],
    category: 'security',
    type: 'text',
    defaultValue: '',
    placeholder: '192.168.1.1, 10.0.0.0/8',
  },
  {
    id: 'ipBlacklist',
    title: 'IP Blacklist',
    description: 'Blocked IP addresses (comma-separated)',
    keywords: ['ip', 'blacklist', 'block'],
    category: 'security',
    type: 'text',
    defaultValue: '',
    placeholder: '192.168.1.100, 10.0.0.50',
  },
  {
    id: 'geoBlocking',
    title: 'Geo-blocking',
    description: 'Enable geographic access restrictions',
    keywords: ['geo', 'blocking', 'location'],
    category: 'security',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'allowedCountries',
    title: 'Allowed Countries',
    description: 'Allowed country codes (comma-separated)',
    keywords: ['country', 'geo', 'allowed'],
    category: 'security',
    type: 'text',
    defaultValue: '',
    placeholder: 'US, CA, GB',
  },
  {
    id: 'blockedCountries',
    title: 'Blocked Countries',
    description: 'Blocked country codes (comma-separated)',
    keywords: ['country', 'geo', 'blocked'],
    category: 'security',
    type: 'text',
    defaultValue: '',
    placeholder: 'XX, YY',
  },
  {
    id: 'rateLimitByIp',
    title: 'Rate Limit by IP',
    description: 'Apply rate limits per IP address',
    keywords: ['rate', 'limit', 'ip'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'bruteForceProtection',
    title: 'Brute Force Protection',
    description: 'Enable brute force attack protection',
    keywords: ['brute', 'force', 'protection'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'maxLoginAttempts',
    title: 'Max Login Attempts',
    description: 'Maximum failed login attempts',
    keywords: ['login', 'attempts', 'max'],
    category: 'security',
    type: 'number',
    defaultValue: 5,
    min: 1,
    max: 20,
  },
  {
    id: 'lockoutDuration',
    title: 'Lockout Duration',
    description: 'Account lockout duration after max attempts',
    keywords: ['lockout', 'duration', 'ban'],
    category: 'security',
    type: 'number',
    defaultValue: 900,
    min: 60,
    max: 3600,
    unit: 'seconds',
  },
  {
    id: 'passwordPolicy',
    title: 'Password Policy',
    description: 'Password strength requirements',
    keywords: ['password', 'policy', 'strength'],
    category: 'security',
    type: 'select',
    defaultValue: 'medium',
    options: [
      { value: 'weak', label: 'Weak' },
      { value: 'medium', label: 'Medium' },
      { value: 'strong', label: 'Strong' },
      { value: 'very-strong', label: 'Very Strong' },
    ],
  },
  {
    id: 'twoFactorAuth',
    title: 'Two-Factor Authentication',
    description: 'Require 2FA for authentication',
    keywords: ['2fa', 'two-factor', 'mfa'],
    category: 'security',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'auditLogging',
    title: 'Audit Logging',
    description: 'Enable security audit logging',
    keywords: ['audit', 'logging', 'security'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'sensitiveDataMasking',
    title: 'Sensitive Data Masking',
    description: 'Mask sensitive data in logs',
    keywords: ['masking', 'sensitive', 'privacy'],
    category: 'security',
    type: 'boolean',
    defaultValue: true,
  },

  // Diagnostics & Logging (30 controls)
  {
    id: 'loggingEnabled',
    title: 'Logging Enabled',
    description: 'Enable diagnostic logging',
    keywords: ['logging', 'debug', 'diagnostics'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'logLevel',
    title: 'Log Level',
    description: 'Minimum log level to record',
    keywords: ['log', 'level', 'verbosity'],
    category: 'diagnostics',
    type: 'select',
    defaultValue: 'info',
    options: [
      { value: 'trace', label: 'Trace' },
      { value: 'debug', label: 'Debug' },
      { value: 'info', label: 'Info' },
      { value: 'warn', label: 'Warning' },
      { value: 'error', label: 'Error' },
      { value: 'fatal', label: 'Fatal' },
    ],
  },
  {
    id: 'consoleLogging',
    title: 'Console Logging',
    description: 'Output logs to browser console',
    keywords: ['console', 'logging', 'output'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'remoteLogging',
    title: 'Remote Logging',
    description: 'Send logs to remote server',
    keywords: ['remote', 'logging', 'server'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'remoteLogEndpoint',
    title: 'Remote Log Endpoint',
    description: 'Remote logging server URL',
    keywords: ['remote', 'log', 'endpoint'],
    category: 'diagnostics',
    type: 'text',
    defaultValue: '',
    placeholder: 'https://logs.example.com/api',
  },
  {
    id: 'logFormat',
    title: 'Log Format',
    description: 'Log message format',
    keywords: ['log', 'format', 'structure'],
    category: 'diagnostics',
    type: 'select',
    defaultValue: 'json',
    options: [
      { value: 'text', label: 'Plain Text' },
      { value: 'json', label: 'JSON' },
      { value: 'structured', label: 'Structured' },
    ],
  },
  {
    id: 'timestampFormat',
    title: 'Timestamp Format',
    description: 'Log timestamp format',
    keywords: ['timestamp', 'format', 'time'],
    category: 'diagnostics',
    type: 'select',
    defaultValue: 'iso8601',
    options: [
      { value: 'iso8601', label: 'ISO 8601' },
      { value: 'unix', label: 'Unix Timestamp' },
      { value: 'relative', label: 'Relative Time' },
    ],
  },
  {
    id: 'logRotation',
    title: 'Log Rotation',
    description: 'Enable log rotation',
    keywords: ['log', 'rotation', 'archive'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'maxLogSize',
    title: 'Max Log Size',
    description: 'Maximum log file size',
    keywords: ['log', 'size', 'max'],
    category: 'diagnostics',
    type: 'number',
    defaultValue: 10,
    min: 1,
    max: 100,
    unit: 'MB',
  },
  {
    id: 'maxLogFiles',
    title: 'Max Log Files',
    description: 'Maximum number of log files to keep',
    keywords: ['log', 'files', 'max'],
    category: 'diagnostics',
    type: 'number',
    defaultValue: 5,
    min: 1,
    max: 20,
  },
  {
    id: 'performanceMonitoring',
    title: 'Performance Monitoring',
    description: 'Enable performance metrics collection',
    keywords: ['performance', 'monitoring', 'metrics'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'metricsInterval',
    title: 'Metrics Interval',
    description: 'Metrics collection interval',
    keywords: ['metrics', 'interval', 'collection'],
    category: 'diagnostics',
    type: 'number',
    defaultValue: 60,
    min: 10,
    max: 600,
    unit: 'seconds',
  },
  {
    id: 'requestTracing',
    title: 'Request Tracing',
    description: 'Enable distributed request tracing',
    keywords: ['tracing', 'request', 'distributed'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'traceIdHeader',
    title: 'Trace ID Header',
    description: 'HTTP header for trace IDs',
    keywords: ['trace', 'id', 'header'],
    category: 'diagnostics',
    type: 'text',
    defaultValue: 'X-Trace-Id',
    placeholder: 'Header name',
  },
  {
    id: 'spanSampling',
    title: 'Span Sampling Rate',
    description: 'Percentage of traces to sample',
    keywords: ['span', 'sampling', 'rate'],
    category: 'diagnostics',
    type: 'slider',
    defaultValue: 10,
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'errorReporting',
    title: 'Error Reporting',
    description: 'Enable automatic error reporting',
    keywords: ['error', 'reporting', 'crash'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'errorReportingEndpoint',
    title: 'Error Reporting Endpoint',
    description: 'Error reporting service URL',
    keywords: ['error', 'reporting', 'endpoint'],
    category: 'diagnostics',
    type: 'text',
    defaultValue: '',
    placeholder: 'https://errors.example.com/api',
  },
  {
    id: 'stackTraces',
    title: 'Stack Traces',
    description: 'Include stack traces in error logs',
    keywords: ['stack', 'trace', 'error'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'sourceMapSupport',
    title: 'Source Map Support',
    description: 'Enable source map resolution',
    keywords: ['source', 'map', 'debug'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'debugMode',
    title: 'Debug Mode',
    description: 'Enable verbose debug output',
    keywords: ['debug', 'mode', 'verbose'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'verboseErrors',
    title: 'Verbose Errors',
    description: 'Include detailed error information',
    keywords: ['verbose', 'errors', 'details'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'networkInspector',
    title: 'Network Inspector',
    description: 'Enable network request inspection',
    keywords: ['network', 'inspector', 'debug'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'requestLogging',
    title: 'Request Logging',
    description: 'Log all HTTP requests',
    keywords: ['request', 'logging', 'http'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'responseLogging',
    title: 'Response Logging',
    description: 'Log all HTTP responses',
    keywords: ['response', 'logging', 'http'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'payloadLogging',
    title: 'Payload Logging',
    description: 'Log request/response payloads',
    keywords: ['payload', 'logging', 'body'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'headerLogging',
    title: 'Header Logging',
    description: 'Log HTTP headers',
    keywords: ['header', 'logging', 'http'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'timingMetrics',
    title: 'Timing Metrics',
    description: 'Collect detailed timing metrics',
    keywords: ['timing', 'metrics', 'performance'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'memoryProfiling',
    title: 'Memory Profiling',
    description: 'Enable memory usage profiling',
    keywords: ['memory', 'profiling', 'heap'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'cpuProfiling',
    title: 'CPU Profiling',
    description: 'Enable CPU usage profiling',
    keywords: ['cpu', 'profiling', 'performance'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'healthChecks',
    title: 'Health Checks',
    description: 'Enable periodic health checks',
    keywords: ['health', 'check', 'monitoring'],
    category: 'diagnostics',
    type: 'boolean',
    defaultValue: true,
  },

  // Feature Flags (30 controls)
  {
    id: 'featureQueryCaching',
    title: 'Query Caching',
    description: 'Enable query response caching',
    keywords: ['feature', 'query', 'caching'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureUpdateBatching',
    title: 'Update Batching',
    description: 'Enable update call batching',
    keywords: ['feature', 'update', 'batching'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureAutoRetry',
    title: 'Auto Retry',
    description: 'Enable automatic request retry',
    keywords: ['feature', 'retry', 'auto'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureOfflineMode',
    title: 'Offline Mode',
    description: 'Enable offline operation support',
    keywords: ['feature', 'offline', 'mode'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureSyncQueue',
    title: 'Sync Queue',
    description: 'Enable offline sync queue',
    keywords: ['feature', 'sync', 'queue'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureOptimisticUpdates',
    title: 'Optimistic Updates',
    description: 'Enable optimistic UI updates',
    keywords: ['feature', 'optimistic', 'updates'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureRealtime',
    title: 'Realtime Updates',
    description: 'Enable realtime data synchronization',
    keywords: ['feature', 'realtime', 'sync'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureWebSockets',
    title: 'WebSocket Support',
    description: 'Enable WebSocket connections',
    keywords: ['feature', 'websocket', 'ws'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureServerSentEvents',
    title: 'Server-Sent Events',
    description: 'Enable SSE for push updates',
    keywords: ['feature', 'sse', 'events'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureGraphQL',
    title: 'GraphQL Support',
    description: 'Enable GraphQL query interface',
    keywords: ['feature', 'graphql', 'query'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureREST',
    title: 'REST API',
    description: 'Enable REST API interface',
    keywords: ['feature', 'rest', 'api'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureGRPC',
    title: 'gRPC Support',
    description: 'Enable gRPC protocol',
    keywords: ['feature', 'grpc', 'protocol'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureCompression',
    title: 'Response Compression',
    description: 'Enable response compression',
    keywords: ['feature', 'compression', 'gzip'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureEncryption',
    title: 'End-to-End Encryption',
    description: 'Enable E2E encryption',
    keywords: ['feature', 'encryption', 'e2e'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureAnalytics',
    title: 'Analytics',
    description: 'Enable usage analytics',
    keywords: ['feature', 'analytics', 'tracking'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureTelemetry',
    title: 'Telemetry',
    description: 'Enable telemetry data collection',
    keywords: ['feature', 'telemetry', 'metrics'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureABTesting',
    title: 'A/B Testing',
    description: 'Enable A/B testing framework',
    keywords: ['feature', 'ab', 'testing'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureFeatureToggles',
    title: 'Feature Toggles',
    description: 'Enable dynamic feature toggles',
    keywords: ['feature', 'toggles', 'flags'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureCanaryDeployment',
    title: 'Canary Deployment',
    description: 'Enable canary deployment support',
    keywords: ['feature', 'canary', 'deployment'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureBlueGreen',
    title: 'Blue-Green Deployment',
    description: 'Enable blue-green deployment',
    keywords: ['feature', 'blue', 'green'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureRollback',
    title: 'Auto Rollback',
    description: 'Enable automatic rollback on errors',
    keywords: ['feature', 'rollback', 'auto'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureVersioning',
    title: 'API Versioning',
    description: 'Enable API version management',
    keywords: ['feature', 'versioning', 'api'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureDeprecation',
    title: 'Deprecation Warnings',
    description: 'Show deprecation warnings',
    keywords: ['feature', 'deprecation', 'warnings'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureBackwardCompatibility',
    title: 'Backward Compatibility',
    description: 'Enable backward compatibility mode',
    keywords: ['feature', 'backward', 'compatibility'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureMigrationMode',
    title: 'Migration Mode',
    description: 'Enable data migration support',
    keywords: ['feature', 'migration', 'data'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureSchemaValidation',
    title: 'Schema Validation',
    description: 'Enable schema validation',
    keywords: ['feature', 'schema', 'validation'],
    category: 'features',
    type: 'boolean',
    defaultValue: true,
  },
  {
    id: 'featureTypeChecking',
    title: 'Runtime Type Checking',
    description: 'Enable runtime type validation',
    keywords: ['feature', 'type', 'checking'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureContractTesting',
    title: 'Contract Testing',
    description: 'Enable API contract testing',
    keywords: ['feature', 'contract', 'testing'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureMockMode',
    title: 'Mock Mode',
    description: 'Enable mock data mode',
    keywords: ['feature', 'mock', 'testing'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'featureSandbox',
    title: 'Sandbox Mode',
    description: 'Enable sandbox environment',
    keywords: ['feature', 'sandbox', 'testing'],
    category: 'features',
    type: 'boolean',
    defaultValue: false,
  },

  // Experimental (30 controls)
  {
    id: 'expQuantumResistant',
    title: 'Quantum-Resistant Crypto',
    description: 'Enable post-quantum cryptography',
    keywords: ['experimental', 'quantum', 'crypto'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expAIOptimization',
    title: 'AI-Powered Optimization',
    description: 'Enable AI-based performance tuning',
    keywords: ['experimental', 'ai', 'optimization'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expPredictivePrefetch',
    title: 'Predictive Prefetching',
    description: 'AI-powered predictive data prefetching',
    keywords: ['experimental', 'predictive', 'prefetch'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expEdgeComputing',
    title: 'Edge Computing',
    description: 'Enable edge computation offloading',
    keywords: ['experimental', 'edge', 'computing'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expP2PSync',
    title: 'P2P Synchronization',
    description: 'Enable peer-to-peer data sync',
    keywords: ['experimental', 'p2p', 'sync'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expBlockchainVerification',
    title: 'Blockchain Verification',
    description: 'Enable blockchain-based verification',
    keywords: ['experimental', 'blockchain', 'verification'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expZeroKnowledgeProofs',
    title: 'Zero-Knowledge Proofs',
    description: 'Enable ZK proof generation',
    keywords: ['experimental', 'zk', 'proofs'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expHomomorphicEncryption',
    title: 'Homomorphic Encryption',
    description: 'Enable computation on encrypted data',
    keywords: ['experimental', 'homomorphic', 'encryption'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expFederatedLearning',
    title: 'Federated Learning',
    description: 'Enable federated ML training',
    keywords: ['experimental', 'federated', 'learning'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expDifferentialPrivacy',
    title: 'Differential Privacy',
    description: 'Enable differential privacy mechanisms',
    keywords: ['experimental', 'differential', 'privacy'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expSecureMultiparty',
    title: 'Secure Multiparty Computation',
    description: 'Enable MPC protocols',
    keywords: ['experimental', 'mpc', 'secure'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expThresholdCrypto',
    title: 'Threshold Cryptography',
    description: 'Enable threshold signature schemes',
    keywords: ['experimental', 'threshold', 'crypto'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expVerifiableComputation',
    title: 'Verifiable Computation',
    description: 'Enable computation verification',
    keywords: ['experimental', 'verifiable', 'computation'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expTrustedExecution',
    title: 'Trusted Execution Environment',
    description: 'Enable TEE support',
    keywords: ['experimental', 'tee', 'trusted'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expConfidentialComputing',
    title: 'Confidential Computing',
    description: 'Enable confidential computing features',
    keywords: ['experimental', 'confidential', 'computing'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expQuantumRNG',
    title: 'Quantum Random Number Generator',
    description: 'Use quantum RNG for randomness',
    keywords: ['experimental', 'quantum', 'rng'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expBiometricAuth',
    title: 'Biometric Authentication',
    description: 'Enable biometric authentication',
    keywords: ['experimental', 'biometric', 'auth'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expBehavioralAnalytics',
    title: 'Behavioral Analytics',
    description: 'Enable user behavior analysis',
    keywords: ['experimental', 'behavioral', 'analytics'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expAnomalyDetection',
    title: 'Anomaly Detection',
    description: 'Enable ML-based anomaly detection',
    keywords: ['experimental', 'anomaly', 'detection'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expThreatIntelligence',
    title: 'Threat Intelligence',
    description: 'Enable threat intelligence feeds',
    keywords: ['experimental', 'threat', 'intelligence'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expAutoScaling',
    title: 'Auto-Scaling',
    description: 'Enable automatic resource scaling',
    keywords: ['experimental', 'auto', 'scaling'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expLoadPrediction',
    title: 'Load Prediction',
    description: 'Enable ML-based load prediction',
    keywords: ['experimental', 'load', 'prediction'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expAdaptiveRouting',
    title: 'Adaptive Routing',
    description: 'Enable intelligent request routing',
    keywords: ['experimental', 'adaptive', 'routing'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expChaosEngineering',
    title: 'Chaos Engineering',
    description: 'Enable chaos testing features',
    keywords: ['experimental', 'chaos', 'engineering'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expFaultInjection',
    title: 'Fault Injection',
    description: 'Enable controlled fault injection',
    keywords: ['experimental', 'fault', 'injection'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expTimeTravel',
    title: 'Time Travel Debugging',
    description: 'Enable time-travel debugging',
    keywords: ['experimental', 'time', 'travel'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expReplayMode',
    title: 'Request Replay',
    description: 'Enable request replay for debugging',
    keywords: ['experimental', 'replay', 'debug'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expSnapshotMode',
    title: 'State Snapshots',
    description: 'Enable state snapshot capture',
    keywords: ['experimental', 'snapshot', 'state'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expVersionControl',
    title: 'Built-in Version Control',
    description: 'Enable integrated version control',
    keywords: ['experimental', 'version', 'control'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'expCollaboration',
    title: 'Real-time Collaboration',
    description: 'Enable collaborative editing',
    keywords: ['experimental', 'collaboration', 'realtime'],
    category: 'experimental',
    type: 'boolean',
    defaultValue: false,
  },

  // Advanced Settings (30 controls)
  {
    id: 'advLowLevelAPI',
    title: 'Low-Level API Access',
    description: 'Enable direct low-level API access',
    keywords: ['advanced', 'low-level', 'api'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advRawProtocol',
    title: 'Raw Protocol Mode',
    description: 'Enable raw protocol communication',
    keywords: ['advanced', 'raw', 'protocol'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advCustomSerializer',
    title: 'Custom Serializer',
    description: 'Use custom data serialization',
    keywords: ['advanced', 'serializer', 'custom'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advBinaryProtocol',
    title: 'Binary Protocol',
    description: 'Enable binary protocol mode',
    keywords: ['advanced', 'binary', 'protocol'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advMessagePacking',
    title: 'Message Packing',
    description: 'Enable MessagePack encoding',
    keywords: ['advanced', 'messagepack', 'encoding'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advProtobuf',
    title: 'Protocol Buffers',
    description: 'Enable Protobuf serialization',
    keywords: ['advanced', 'protobuf', 'serialization'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advCustomCodec',
    title: 'Custom Codec',
    description: 'Use custom encoding/decoding',
    keywords: ['advanced', 'codec', 'custom'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advMemoryManagement',
    title: 'Manual Memory Management',
    description: 'Enable manual memory control',
    keywords: ['advanced', 'memory', 'manual'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advBufferPooling',
    title: 'Buffer Pooling',
    description: 'Enable buffer pool management',
    keywords: ['advanced', 'buffer', 'pooling'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advZeroCopy',
    title: 'Zero-Copy Operations',
    description: 'Enable zero-copy data transfer',
    keywords: ['advanced', 'zero-copy', 'performance'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advDirectMemoryAccess',
    title: 'Direct Memory Access',
    description: 'Enable DMA operations',
    keywords: ['advanced', 'dma', 'memory'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advKernelBypass',
    title: 'Kernel Bypass',
    description: 'Enable kernel bypass networking',
    keywords: ['advanced', 'kernel', 'bypass'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advRDMA',
    title: 'RDMA Support',
    description: 'Enable Remote Direct Memory Access',
    keywords: ['advanced', 'rdma', 'network'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advCustomAllocator',
    title: 'Custom Allocator',
    description: 'Use custom memory allocator',
    keywords: ['advanced', 'allocator', 'memory'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advLockFree',
    title: 'Lock-Free Data Structures',
    description: 'Enable lock-free algorithms',
    keywords: ['advanced', 'lock-free', 'concurrent'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advWaitFree',
    title: 'Wait-Free Operations',
    description: 'Enable wait-free guarantees',
    keywords: ['advanced', 'wait-free', 'concurrent'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advAtomicOperations',
    title: 'Atomic Operations',
    description: 'Enable hardware atomic operations',
    keywords: ['advanced', 'atomic', 'hardware'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advSIMD',
    title: 'SIMD Instructions',
    description: 'Enable SIMD vectorization',
    keywords: ['advanced', 'simd', 'vectorization'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advGPUAcceleration',
    title: 'GPU Acceleration',
    description: 'Enable GPU-accelerated operations',
    keywords: ['advanced', 'gpu', 'acceleration'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advWebAssembly',
    title: 'WebAssembly Mode',
    description: 'Enable WebAssembly execution',
    keywords: ['advanced', 'wasm', 'webassembly'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advJIT',
    title: 'JIT Compilation',
    description: 'Enable just-in-time compilation',
    keywords: ['advanced', 'jit', 'compilation'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advAOT',
    title: 'AOT Compilation',
    description: 'Enable ahead-of-time compilation',
    keywords: ['advanced', 'aot', 'compilation'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advInlining',
    title: 'Aggressive Inlining',
    description: 'Enable aggressive function inlining',
    keywords: ['advanced', 'inlining', 'optimization'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advUnrolling',
    title: 'Loop Unrolling',
    description: 'Enable loop unrolling optimization',
    keywords: ['advanced', 'unrolling', 'loop'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advPrefetching',
    title: 'Hardware Prefetching',
    description: 'Enable hardware prefetch hints',
    keywords: ['advanced', 'prefetch', 'hardware'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advBranchPrediction',
    title: 'Branch Prediction Hints',
    description: 'Enable branch prediction optimization',
    keywords: ['advanced', 'branch', 'prediction'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advCacheLineAlignment',
    title: 'Cache Line Alignment',
    description: 'Enable cache line alignment',
    keywords: ['advanced', 'cache', 'alignment'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advNUMA',
    title: 'NUMA Awareness',
    description: 'Enable NUMA-aware allocation',
    keywords: ['advanced', 'numa', 'memory'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advHugepages',
    title: 'Huge Pages',
    description: 'Enable huge page support',
    keywords: ['advanced', 'hugepages', 'memory'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
  {
    id: 'advCustomScheduler',
    title: 'Custom Scheduler',
    description: 'Use custom task scheduler',
    keywords: ['advanced', 'scheduler', 'custom'],
    category: 'advanced',
    type: 'boolean',
    defaultValue: false,
  },
];
