/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T__1 = IDL.Variant({
  'unauthorizedAttempt' : IDL.Null,
  'loginAttempt' : IDL.Null,
  'permissionChange' : IDL.Null,
  'superuserPrivilegeChange' : IDL.Null,
  'dataExport' : IDL.Null,
  'general' : IDL.Null,
  'accountChange' : IDL.Null,
  'configUpload' : IDL.Null,
  'dataImport' : IDL.Null,
});
export const Time = IDL.Int;
export const T__2 = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const T = IDL.Record({
  'sessionData' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'actionType' : T__1,
  'timestamp' : Time,
  'details' : IDL.Text,
  'deviceInfo' : IDL.Opt(IDL.Text),
  'success' : IDL.Opt(IDL.Bool),
  'severity' : T__2,
  'ipAddress' : IDL.Opt(IDL.Text),
});
export const T__4 = IDL.Record({
  'user' : IDL.Opt(IDL.Principal),
  'actionType' : IDL.Opt(T__1),
  'toDate' : IDL.Opt(Time),
  'fromDate' : IDL.Opt(Time),
  'severity' : IDL.Opt(T__2),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const T__3 = IDL.Record({
  'enabled' : IDL.Bool,
  'endpointUrl' : IDL.Opt(IDL.Text),
});
export const InstanceContext = IDL.Record({
  'contextPrincipal' : IDL.Principal,
  'contextTimestamp' : Time,
});
export const IcpController = IDL.Record({
  'principal' : IDL.Principal,
  'revokedTimestamp' : IDL.Opt(Time),
  'name' : IDL.Opt(IDL.Text),
  'createdBy' : IDL.Opt(IDL.Principal),
  'description' : IDL.Opt(IDL.Text),
  'roleAssigned' : IDL.Bool,
  'lastActiveTimestamp' : IDL.Opt(Time),
  'assignedTimestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'configureExternalBroadcasting' : IDL.Func(
      [IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'exportAuditLogToJson' : IDL.Func([], [IDL.Vec(T)], []),
  'flagUser' : IDL.Func([IDL.Principal], [], []),
  'getAppController' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAuditLogs' : IDL.Func([T__4], [IDL.Vec(T)], ['query']),
  'getCallerAppControllerStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExternalBroadcastingSettings' : IDL.Func([], [T__3], ['query']),
  'getFlaggedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantIcpControllerRole' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'grantSecurityRole' : IDL.Func([IDL.Principal], [], []),
  'hasIcpControllerRole' : IDL.Func([], [IDL.Bool], ['query']),
  'initialize' : IDL.Func([InstanceContext], [], []),
  'isAppController' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSecurityUser' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserFlagged' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listIcpControllers' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(IcpController)],
      ['query'],
    ),
  'recordAuditEntry' : IDL.Func([T], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'revokeIcpControllerRole' : IDL.Func([IDL.Principal], [], []),
  'revokeSecurityRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unflagUser' : IDL.Func([IDL.Principal], [], []),
  'updateIcpControllerDescription' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T__1 = IDL.Variant({
    'unauthorizedAttempt' : IDL.Null,
    'loginAttempt' : IDL.Null,
    'permissionChange' : IDL.Null,
    'superuserPrivilegeChange' : IDL.Null,
    'dataExport' : IDL.Null,
    'general' : IDL.Null,
    'accountChange' : IDL.Null,
    'configUpload' : IDL.Null,
    'dataImport' : IDL.Null,
  });
  const Time = IDL.Int;
  const T__2 = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const T = IDL.Record({
    'sessionData' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'actionType' : T__1,
    'timestamp' : Time,
    'details' : IDL.Text,
    'deviceInfo' : IDL.Opt(IDL.Text),
    'success' : IDL.Opt(IDL.Bool),
    'severity' : T__2,
    'ipAddress' : IDL.Opt(IDL.Text),
  });
  const T__4 = IDL.Record({
    'user' : IDL.Opt(IDL.Principal),
    'actionType' : IDL.Opt(T__1),
    'toDate' : IDL.Opt(Time),
    'fromDate' : IDL.Opt(Time),
    'severity' : IDL.Opt(T__2),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const T__3 = IDL.Record({
    'enabled' : IDL.Bool,
    'endpointUrl' : IDL.Opt(IDL.Text),
  });
  const InstanceContext = IDL.Record({
    'contextPrincipal' : IDL.Principal,
    'contextTimestamp' : Time,
  });
  const IcpController = IDL.Record({
    'principal' : IDL.Principal,
    'revokedTimestamp' : IDL.Opt(Time),
    'name' : IDL.Opt(IDL.Text),
    'createdBy' : IDL.Opt(IDL.Principal),
    'description' : IDL.Opt(IDL.Text),
    'roleAssigned' : IDL.Bool,
    'lastActiveTimestamp' : IDL.Opt(Time),
    'assignedTimestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'configureExternalBroadcasting' : IDL.Func(
        [IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'exportAuditLogToJson' : IDL.Func([], [IDL.Vec(T)], []),
    'flagUser' : IDL.Func([IDL.Principal], [], []),
    'getAppController' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAuditLogs' : IDL.Func([T__4], [IDL.Vec(T)], ['query']),
    'getCallerAppControllerStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExternalBroadcastingSettings' : IDL.Func([], [T__3], ['query']),
    'getFlaggedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantIcpControllerRole' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'grantSecurityRole' : IDL.Func([IDL.Principal], [], []),
    'hasIcpControllerRole' : IDL.Func([], [IDL.Bool], ['query']),
    'initialize' : IDL.Func([InstanceContext], [], []),
    'isAppController' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSecurityUser' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserFlagged' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listIcpControllers' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(IcpController)],
        ['query'],
      ),
    'recordAuditEntry' : IDL.Func([T], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'revokeIcpControllerRole' : IDL.Func([IDL.Principal], [], []),
    'revokeSecurityRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unflagUser' : IDL.Func([IDL.Principal], [], []),
    'updateIcpControllerDescription' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };