/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Edge {
  'id' : EdgeId,
  'weight' : number,
  'created' : Time,
  'source' : NodeId,
  'directed' : boolean,
  'target' : NodeId,
  'updated' : Time,
}
export type EdgeId = bigint;
export interface IcpController {
  'principal' : Principal,
  'revokedTimestamp' : [] | [Time],
  'name' : [] | [string],
  'createdBy' : [] | [Principal],
  'description' : [] | [string],
  'roleAssigned' : boolean,
  'lastActiveTimestamp' : [] | [Time],
  'assignedTimestamp' : Time,
}
export interface InstanceContext {
  'contextPrincipal' : Principal,
  'contextTimestamp' : Time,
}
export interface Node {
  'x' : number,
  'y' : number,
  'id' : NodeId,
  'created' : Time,
  'nodeLabel' : string,
  'updated' : Time,
}
export type NodeId = bigint;
export interface T {
  'sessionData' : [] | [string],
  'user' : Principal,
  'actionType' : T__1,
  'timestamp' : Time,
  'details' : string,
  'deviceInfo' : [] | [string],
  'success' : [] | [boolean],
  'severity' : T__2,
  'ipAddress' : [] | [string],
}
export type T__1 = { 'unauthorizedAttempt' : null } |
  { 'appControllerTransfer' : null } |
  { 'loginAttempt' : null } |
  { 'permissionChange' : null } |
  { 'superuserPrivilegeChange' : null } |
  { 'dataExport' : null } |
  { 'general' : null } |
  { 'accountChange' : null } |
  { 'configUpload' : null } |
  { 'dataImport' : null } |
  { 'worldWideWebControllerPrivilegeChange' : null };
export type T__2 = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface T__3 { 'enabled' : boolean, 'endpointUrl' : [] | [string] }
export interface T__4 {
  'user' : [] | [Principal],
  'actionType' : [] | [T__1],
  'toDate' : [] | [Time],
  'fromDate' : [] | [Time],
  'severity' : [] | [T__2],
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'configureExternalBroadcasting' : ActorMethod<
    [boolean, [] | [string]],
    undefined
  >,
  'createEdge' : ActorMethod<[NodeId, NodeId, number, boolean], EdgeId>,
  'createNode' : ActorMethod<[string, number, number], NodeId>,
  'deleteEdge' : ActorMethod<[EdgeId], undefined>,
  'deleteNode' : ActorMethod<[NodeId], undefined>,
  'exportAuditLogToJson' : ActorMethod<[], Array<T>>,
  'flagUser' : ActorMethod<[Principal], undefined>,
  'getAllEdges' : ActorMethod<[], Array<Edge>>,
  'getAllNodes' : ActorMethod<[], Array<Node>>,
  'getAllWorldWideWebControllers' : ActorMethod<[], Array<Principal>>,
  'getAppController' : ActorMethod<[], [] | [Principal]>,
  'getAuditLogs' : ActorMethod<[T__4], Array<T>>,
  'getCallerAppControllerStatus' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExternalBroadcastingSettings' : ActorMethod<[], T__3>,
  'getFlaggedUsers' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantIcpControllerRole' : ActorMethod<
    [Principal, [] | [string], [] | [string]],
    undefined
  >,
  'grantSecurityRole' : ActorMethod<[Principal], undefined>,
  'grantWorldWideWebControllerRole' : ActorMethod<[Principal], undefined>,
  'hasIcpControllerRole' : ActorMethod<[], boolean>,
  'hasWorldWideWebControllerRole' : ActorMethod<[], boolean>,
  'initialize' : ActorMethod<[InstanceContext], undefined>,
  'isAppController' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSecurityUser' : ActorMethod<[], boolean>,
  'isUserFlagged' : ActorMethod<[Principal], boolean>,
  'isWorldWideWebController' : ActorMethod<[Principal], boolean>,
  'listIcpControllers' : ActorMethod<[boolean], Array<IcpController>>,
  'recordAuditEntry' : ActorMethod<[T], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'resetAndSetGraph' : ActorMethod<[Array<Node>, Array<Edge>], undefined>,
  'revokeIcpControllerRole' : ActorMethod<[Principal], undefined>,
  'revokeSecurityRole' : ActorMethod<[Principal], undefined>,
  'revokeWorldWideWebControllerRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferAppController' : ActorMethod<[Principal], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unflagUser' : ActorMethod<[Principal], undefined>,
  'updateEdge' : ActorMethod<
    [EdgeId, NodeId, NodeId, number, boolean],
    undefined
  >,
  'updateIcpControllerDescription' : ActorMethod<
    [Principal, string, [] | [string]],
    undefined
  >,
  'updateNode' : ActorMethod<[NodeId, string, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];