/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InstanceContext {
  'contextPrincipal' : Principal,
  'contextTimestamp' : Time,
}
export interface T {
  'sessionData' : [] | [string],
  'user' : Principal,
  'actionType' : T__1,
  'timestamp' : Time,
  'details' : string,
  'deviceInfo' : [] | [string],
  'success' : [] | [boolean],
  'severity' : T__2,
  'ipAddress' : [] | [string],
}
export type T__1 = { 'unauthorizedAttempt' : null } |
  { 'loginAttempt' : null } |
  { 'permissionChange' : null } |
  { 'dataExport' : null } |
  { 'general' : null } |
  { 'accountChange' : null } |
  { 'configUpload' : null } |
  { 'dataImport' : null };
export type T__2 = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface T__3 { 'enabled' : boolean, 'endpointUrl' : [] | [string] }
export interface T__4 {
  'user' : [] | [Principal],
  'actionType' : [] | [T__1],
  'toDate' : [] | [Time],
  'fromDate' : [] | [Time],
  'severity' : [] | [T__2],
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'configureExternalBroadcasting' : ActorMethod<
    [boolean, [] | [string]],
    undefined
  >,
  'exportAuditLogToJson' : ActorMethod<[], Array<T>>,
  'flagUser' : ActorMethod<[Principal], undefined>,
  'getAuditLogs' : ActorMethod<[T__4], Array<T>>,
  'getCallerAppControllerStatus' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExternalBroadcastingSettings' : ActorMethod<[], T__3>,
  'getFlaggedUsers' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantSecurityRole' : ActorMethod<[Principal], undefined>,
  'initialize' : ActorMethod<[InstanceContext], undefined>,
  'isAppController' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSecurityUser' : ActorMethod<[], boolean>,
  'isUserFlagged' : ActorMethod<[Principal], boolean>,
  'recordAuditEntry' : ActorMethod<[T], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'revokeSecurityRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unflagUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];