/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface T__4 {
    user?: Principal;
    actionType?: T__1;
    toDate?: Time;
    fromDate?: Time;
    severity?: T__2;
}
export interface T__3 {
    enabled: boolean;
    endpointUrl?: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface T {
    sessionData?: string;
    user: Principal;
    actionType: T__1;
    timestamp: Time;
    details: string;
    deviceInfo?: string;
    success?: boolean;
    severity: T__2;
    ipAddress?: string;
}
export interface InstanceContext {
    contextPrincipal: Principal;
    contextTimestamp: Time;
}
export interface UserProfile {
    name: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum T__1 {
    unauthorizedAttempt = "unauthorizedAttempt",
    loginAttempt = "loginAttempt",
    permissionChange = "permissionChange",
    dataExport = "dataExport",
    general = "general",
    accountChange = "accountChange",
    configUpload = "configUpload",
    dataImport = "dataImport"
}
export enum T__2 {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    configureExternalBroadcasting(enabled: boolean, endpointUrl: string | null): Promise<void>;
    exportAuditLogToJson(): Promise<Array<T>>;
    flagUser(user: Principal): Promise<void>;
    getAuditLogs(filter: T__4): Promise<Array<T>>;
    getCallerAppControllerStatus(): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExternalBroadcastingSettings(): Promise<T__3>;
    getFlaggedUsers(): Promise<Array<Principal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantSecurityRole(target: Principal): Promise<void>;
    initialize(context: InstanceContext): Promise<void>;
    isAppController(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isSecurityUser(): Promise<boolean>;
    isUserFlagged(user: Principal): Promise<boolean>;
    recordAuditEntry(entry: T): Promise<void>;
    removeUser(user: Principal): Promise<void>;
    revokeSecurityRole(target: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unflagUser(user: Principal): Promise<void>;
}
import type { T as _T, T__1 as _T__1, T__2 as _T__2, T__3 as _T__3, T__4 as _T__4, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async configureExternalBroadcasting(arg0: boolean, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.configureExternalBroadcasting(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.configureExternalBroadcasting(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async exportAuditLogToJson(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAuditLogToJson();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAuditLogToJson();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async flagUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagUser(arg0);
            return result;
        }
    }
    async getAuditLogs(arg0: T__4): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(to_candid_T__4_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(to_candid_T__4_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAppControllerStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAppControllerStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAppControllerStatus();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExternalBroadcastingSettings(): Promise<T__3> {
        if (this.processError) {
            try {
                const result = await this.actor.getExternalBroadcastingSettings();
                return from_candid_T__3_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExternalBroadcastingSettings();
            return from_candid_T__3_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlaggedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedUsers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantSecurityRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantSecurityRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantSecurityRole(arg0);
            return result;
        }
    }
    async initialize(arg0: InstanceContext): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize(arg0);
            return result;
        }
    }
    async isAppController(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAppController(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAppController(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSecurityUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSecurityUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSecurityUser();
            return result;
        }
    }
    async isUserFlagged(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserFlagged(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserFlagged(arg0);
            return result;
        }
    }
    async recordAuditEntry(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAuditEntry(to_candid_T_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAuditEntry(to_candid_T_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removeUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async revokeSecurityRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeSecurityRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeSecurityRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unflagUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unflagUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unflagUser(arg0);
            return result;
        }
    }
}
function from_candid_T__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_T__2_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): T__2 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_T__3_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__3): T__3 {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_T_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enabled: boolean;
    endpointUrl: [] | [string];
}): {
    enabled: boolean;
    endpointUrl?: string;
} {
    return {
        enabled: value.enabled,
        endpointUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.endpointUrl))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionData: [] | [string];
    user: Principal;
    actionType: _T__1;
    timestamp: _Time;
    details: string;
    deviceInfo: [] | [string];
    success: [] | [boolean];
    severity: _T__2;
    ipAddress: [] | [string];
}): {
    sessionData?: string;
    user: Principal;
    actionType: T__1;
    timestamp: Time;
    details: string;
    deviceInfo?: string;
    success?: boolean;
    severity: T__2;
    ipAddress?: string;
} {
    return {
        sessionData: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.sessionData)),
        user: value.user,
        actionType: from_candid_T__1_n8(_uploadFile, _downloadFile, value.actionType),
        timestamp: value.timestamp,
        details: value.details,
        deviceInfo: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.deviceInfo)),
        success: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.success)),
        severity: from_candid_T__2_n11(_uploadFile, _downloadFile, value.severity),
        ipAddress: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.ipAddress))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): T__2 {
    return "warning" in value ? T__2.warning : "info" in value ? T__2.info : "critical" in value ? T__2.critical : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unauthorizedAttempt: null;
} | {
    loginAttempt: null;
} | {
    permissionChange: null;
} | {
    dataExport: null;
} | {
    general: null;
} | {
    accountChange: null;
} | {
    configUpload: null;
} | {
    dataImport: null;
}): T__1 {
    return "unauthorizedAttempt" in value ? T__1.unauthorizedAttempt : "loginAttempt" in value ? T__1.loginAttempt : "permissionChange" in value ? T__1.permissionChange : "dataExport" in value ? T__1.dataExport : "general" in value ? T__1.general : "accountChange" in value ? T__1.accountChange : "configUpload" in value ? T__1.configUpload : "dataImport" in value ? T__1.dataImport : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n5(_uploadFile, _downloadFile, x));
}
function to_candid_T__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): _T__1 {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_T__2_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__2): _T__2 {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_T__4_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__4): _T__4 {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_T_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user?: Principal;
    actionType?: T__1;
    toDate?: Time;
    fromDate?: Time;
    severity?: T__2;
}): {
    user: [] | [Principal];
    actionType: [] | [_T__1];
    toDate: [] | [_Time];
    fromDate: [] | [_Time];
    severity: [] | [_T__2];
} {
    return {
        user: value.user ? candid_some(value.user) : candid_none(),
        actionType: value.actionType ? candid_some(to_candid_T__1_n15(_uploadFile, _downloadFile, value.actionType)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        severity: value.severity ? candid_some(to_candid_T__2_n17(_uploadFile, _downloadFile, value.severity)) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionData?: string;
    user: Principal;
    actionType: T__1;
    timestamp: Time;
    details: string;
    deviceInfo?: string;
    success?: boolean;
    severity: T__2;
    ipAddress?: string;
}): {
    sessionData: [] | [string];
    user: Principal;
    actionType: _T__1;
    timestamp: _Time;
    details: string;
    deviceInfo: [] | [string];
    success: [] | [boolean];
    severity: _T__2;
    ipAddress: [] | [string];
} {
    return {
        sessionData: value.sessionData ? candid_some(value.sessionData) : candid_none(),
        user: value.user,
        actionType: to_candid_T__1_n15(_uploadFile, _downloadFile, value.actionType),
        timestamp: value.timestamp,
        details: value.details,
        deviceInfo: value.deviceInfo ? candid_some(value.deviceInfo) : candid_none(),
        success: value.success ? candid_some(value.success) : candid_none(),
        severity: to_candid_T__2_n17(_uploadFile, _downloadFile, value.severity),
        ipAddress: value.ipAddress ? candid_some(value.ipAddress) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): {
    unauthorizedAttempt: null;
} | {
    loginAttempt: null;
} | {
    permissionChange: null;
} | {
    dataExport: null;
} | {
    general: null;
} | {
    accountChange: null;
} | {
    configUpload: null;
} | {
    dataImport: null;
} {
    return value == T__1.unauthorizedAttempt ? {
        unauthorizedAttempt: null
    } : value == T__1.loginAttempt ? {
        loginAttempt: null
    } : value == T__1.permissionChange ? {
        permissionChange: null
    } : value == T__1.dataExport ? {
        dataExport: null
    } : value == T__1.general ? {
        general: null
    } : value == T__1.accountChange ? {
        accountChange: null
    } : value == T__1.configUpload ? {
        configUpload: null
    } : value == T__1.dataImport ? {
        dataImport: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__2): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == T__2.warning ? {
        warning: null
    } : value == T__2.info ? {
        info: null
    } : value == T__2.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
